modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Syntactic Wizardry.'''
[[mixins]]
config="syntacticwizardry.mixins.json"
[[mixins]]
config="arcane_builder_compat.mixins.json"
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[4.7.5.1,5)"
ordering="AFTER"
side="BOTH"
